### PR TITLE
Using CMake for cross platform Makefile generation

### PR DESCRIPTION
**Pull request by domesticmouse**
Hey @johnpryan,

I'm investigating what it will take to make it possible to build `.dylib`s that dart can use on macOS. My first step is to migrate from hand rolled make scripts to CMake. This makes it simple to generate things like Xcode projects and the like easily.

However, attempting to use Xcode to generate a signed dylib is still causing issues when attempting to load it into a running Dart image, because it looks like macOS requires that the signature of the app and the dylib match.

```bash
$ dart hello.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (dlopen(./hello_library/Debug/libhello.dylib, 1): no suitable image found.  Did find:
        ./hello_library/Debug/libhello.dylib: code signature in (./hello_library/Debug/libhello.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:19:12)
#2      main (file:///Users/brettmorgan/Documents/GitHub/dart-samples/ffi/hello_world/hello.dart:18:36)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

/cc @mjohnsullivan 

ps: I should point out, this hasn't been tested on Windows, as I haven't done C/C++ development on windows in over two decades. =)

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @dcharkes

**Comment by johnpryan** [comment]
It looks like the unit test for hello_world is returning an exit code: https://travis-ci.org/dart-lang/samples/jobs/611675031#L255

**Comment by domesticmouse** [comment]
I'd love some guidance on what travis is doing here. When I attempt to replicate this error condition on my local linux cloudtop instance I see the following:

```bash
$ PKGS='ffi/hello_world' ./tool/travis.sh test
PKG: ffi/hello_world
~/dart-apps/dart-samples/ffi/hello_world ~/dart-apps/dart-samples
Resolving dependencies... (10.9s)
  _fe_analyzer_shared 1.0.0
  analyzer 0.39.1
  args 1.5.2
  async 2.4.0
  boolean_selector 1.0.5
  charcode 1.1.2
  collection 1.14.12
  convert 2.1.1
  coverage 0.13.3+1
  crypto 2.1.3
  csslib 0.16.1
  front_end 0.1.29
  glob 1.2.0
  html 0.14.0+3
  http 0.12.0+2
  http_multi_server 2.1.0
  http_parser 3.1.3
  io 0.3.3
  js 0.6.1+1
  kernel 0.3.29
  logging 0.11.3+2
  matcher 0.12.6
  meta 1.1.8
  mime 0.9.6+3
  multi_server_socket 1.0.2
  node_interop 1.0.3
  node_io 1.0.1+2
  node_preamble 1.4.8
  package_config 1.1.0
  package_resolver 1.0.10
  path 1.6.4
  pedantic 1.8.0+1
  pool 1.4.0
  pub_semver 1.4.2
  shelf 0.7.5
  shelf_packages_handler 1.0.4
  shelf_static 0.2.8
  shelf_web_socket 0.2.3
  source_map_stack_trace 1.1.5
  source_maps 0.10.8
  source_span 1.5.5
  stack_trace 1.9.3
  stream_channel 2.0.0
  string_scanner 1.0.5
  term_glyph 1.1.0
  test 1.9.4
  test_api 0.2.11
  test_core 0.2.15
  typed_data 1.1.6
  vm_service 2.1.1
  watcher 0.9.7+12
  web_socket_channel 1.1.0
  yaml 2.2.0
No dependencies changed.

PKG: ffi/hello_world; TASK: test
pub run test
00:01 +1: All tests passed!                                                                                               
~/dart-apps/dart-samples
```

**Comment by domesticmouse** [comment]
Turns out I needed to add `cmake` to the mix inside of Travis. Makes sense, in retrospect.

**Pull request merged**
