### PR TITLE
* Fix small UseAfterFree issue * Add function that takes struct as parameter

### PR DESCRIPTION
**Pull request by mahesh-hegde**
small changes I made while studying FFI. seeing #145 I think we should update it.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
PTAL @johnpryan

**Review by johnpryan — CHANGES_REQUESTED** [review]
Can you update [structs_test.dart](https://github.com/dart-lang/samples/blob/master/ffi/structs/test/structs_test.dart)?

**Comment by johnpryan** [comment]
I noticed we weren't running tests on this sample, waiting for https://github.com/dart-lang/samples/pull/147 to land

**Comment by mahesh-hegde** [comment]
What did I do wrong? It's passing on my machine.

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Pull request merged**
