### PR TITLE
Allow multiple build for different type of OS.

### PR DESCRIPTION
**Pull request by irvifa**

### CODE REVIEW

**Comment by kevmoo** [comment]
@jakemac53 – is there a way to set this up w/ mono_repo?

**Comment by irvifa** [comment]
If it’s possible then will be good since we don’t need to create an explicit matrix. Expect we of course still can exclude several things that don’t need to be build inside of the job.

**Comment by jakemac53** [comment]
mono_repo does support `os` config yes. It looks just like normal travis config, so inside of a `mono_pkg.yml` file you would do for instance:

```yaml
os:
  - linux
  - windows
  - osx
```

**Comment by irvifa** [comment]
For travis I guess there's also a problem for the Windows dll build however I can't test it on my PC. Please see https://travis-ci.org/github/dart-lang/samples/jobs/670278306?utm_medium=notification&utm_source=github_status

**Comment by domesticmouse** [comment]
I believe this is the start of a fix for https://github.com/dart-lang/samples/issues/46

**Comment by irvifa** [comment]
@domesticmouse Yes it is.. the build config that managed to the job is writing all of the possible combination for all of the build stages. But this is really inefficient, in the term of lines addition. The goal is since this is something like "Hello World" I hope people can easily look at the working example. Any documentation on how mono_repo config works? I'm never use that before. Example of fixes related to FFI is including https://github.com/dart-lang/samples/pull/44.

**Comment by domesticmouse** [comment]
Hey @kevmoo, can you help out with configuring `mono_repo`?

**Comment by jakemac53** [comment]
@irvifa The `os` config is a top level thing that you put in each `mono_pkg.yaml` file - it doesn't go under the travis section.

You can see an example here https://github.com/dart-lang/build/blob/280cd60d74fe24e5a2f01032f4c5ffe3e9c4c5a6/_test/mono_pkg.yaml#L4 which also has examples of overriding specific tasks to run only on a certain os.

**Comment by irvifa** [comment]
@jakemac53 I think that's because of the fact that top level mono_repo is https://github.com/dart-lang/build/blob/280cd60d74fe24e5a2f01032f4c5ffe3e9c4c5a6/mono_repo.yaml So the mono_repo you mentioned before linked to the top level mono_repo, please cmiiw..

**Comment by jakemac53** [comment]
@irvifa I am not sure what you are asking exactly - but what you need to do is put the `os` configuration in _each_  nested `mono_pkg.yaml` file - you configure that per package _even if its the same for every package_. It is not supported in the `mono_repo.yaml` file as a global option.

**Comment by irvifa** [comment]
@jakemac53 Can you help me review this PR? I exclude the windows as allowed to fail since I can't exactly test the `.dl` lib in windows for FFI

**Comment by jakemac53** [comment]
I can send an alternate PR here to show what I mean about the config, give me a minute.

You can also choose which jobs should run on which OS instead of allowing all failures on osx/windows.

**Comment by jakemac53** [comment]
see https://github.com/dart-lang/samples/pull/48

**Pull request closed without merging**
