### PR TITLE
Update ffi/hello_world Dockerfile

### PR DESCRIPTION
**Pull request by dcharkes**

### CODE REVIEW

**Comment by mschwartz** [comment]
I'm not sure how this works for you.

This is what I get when I try to build the Docker container:

image

Same issue for me with https://github.com/dart-lang/samples/pull/109

There's a relative path to ../test_utils that isn't in the Docker image (it's not copied or added in the Dockerfile).  But that's only one bit of the problem - it seems you can't add directories within the Dockerfile that are outside of the directory containing the Dockerfile.

Dockerfiles can be moved up one directory, which is something new-ish.

I am running within WSL2 Linux command line.

**Comment by domesticmouse** [comment]
I've setup to delete the `Dockerfile`s in https://github.com/dart-lang/samples/pull/115 because of https://github.com/dart-lang/samples/pull/115#issuecomment-852650387

**Comment by domesticmouse** [comment]
@mschwartz it worked before `test_utils` was introduced. Simple truth is that anything that isn't tested is broken by design. Unless we want to try adding Docker to the CI, I'm leaning towards to deletion.

**Comment by mschwartz** [comment]
Understood.

You do have Dart CI / unit_test check requirements on the repo.  Not sure if you want that, want to fix the tests, or whatever.

**Comment by domesticmouse** [comment]
Running the FFI samples via Docker isn't tested by the CI, so it broke when the `test_utils` change was made, and not discovered because it wasn't enforced by CI. Given the fix to make Docker work again is to roll back the `test_utils` change, and then figure out if Github Actions supports running Docker, I'm leaning heavily in the direction of just deleting the `Dockerfile`s.

**Comment by domesticmouse** [comment]
I deleted the FFI `Dockerfile`s in https://github.com/dart-lang/samples/pull/115. Closing out this PR.

**Pull request closed without merging**
